import { createContext, useContext, useState } from "react";

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

const translations = {
  ar: {
    // Navigation
    home: "الرئيسية",
    services: "الخدمات",
    booking: "حجز موعد",
    login: "تسجيل الدخول",
    register: "إنشاء حساب",
    profile: "الملف الشخصي",
    dashboard: "لوحة التحكم",
    logout: "تسجيل الخروج",

    // Common
    continue: "استمر",
    cancel: "إلغاء",
    save: "حفظ",
    edit: "تعديل",
    delete: "حذف",
    confirm: "تأكيد",
    loading: "جاري التحميل...",
    next: "التالي",
    previous: "السابق",
    today: "اليوم",
    yes: "نعم",
    no: "لا",
    close: "إغلاق",
    submit: "إرسال",
    search: "بحث",
    filter: "تصفية",
    add: "إضافة",
    update: "تحديث",
    remove: "إزالة",
    view: "عرض",
    back: "رجوع",
    welcome: "مرحباً",
    with: "مع",
    for: "لمدة",
    times: "مرات",
    appointments: "مواعيد",

    // Home
    heroTitle: "أفضل صالون حلاقة في المدينة",
    heroSubtitle: "احجز موعدك الآن واستمتع بأفضل خدمات الحلاقة والعناية",
    bookNow: "احجز الآن",
    readyForBestHaircut: "جاهز لتجربة أفضل حلاقة؟",
    bookNowEnjoyService: "احجز موعدك الآن واستمتع بخدمة استثنائية",
    myBookings: "حجوزاتي",
    createNewAccount: "إنشاء حساب جديد",
    enterPhoneNumber: "أدخل رقم هاتفك:",
    phoneExample: "مثال: 0591234567",
    phoneRequired: "يرجى إدخال رقم الهاتف",
    phoneInvalid: "رقم الهاتف غير صالح (مثال: 0591234567)",
    phoneUpdatedSuccess: "تم تحديث رقم الهاتف بنجاح",
    send: "إرسال",

    // Services
    servicesTitle: "خدماتنا المتميزة",
    servicesSubtitle: "اكتشف مجموعة واسعة من خدمات الحلاقة والعناية المتخصصة",
    allServices: "جميع الخدمات",
    haircut: "قص الشعر",
    beard: "تهذيب اللحية",
    styling: "تصفيف الشعر",
    treatment: "علاجات الشعر",
    package: "باقات خاصة",
    minutes: "دقيقة",
    currency: "شيكل",
    popularService: "خدمة مميزة",
    noServicesInCategory: "لا توجد خدمات في هذه الفئة حالياً",
    didntFindWhatLookingFor: "لم تجد ما تبحث عنه؟",
    contactUsHelp: "تواصل معنا وسنساعدك في العثور على الخدمة المناسبة لك",
    bookFreeConsultation: "احجز استشارة مجانية",
    callUsNow: "اتصل بنا الآن",

    // Authentication
    welcomeBack: "مرحباً بعودتك",
    loginToAccount: "سجل دخولك للوصول إلى حسابك",
    username: "أسم المستخدم",
    enterUsername: "أدخل أسم المستخدم",
    password: "كلمة المرور",
    enterPassword: "أدخل كلمة المرور",
    loggingIn: "جاري تسجيل الدخول...",
    loginWithGoogle: "تسجيل الدخول عبر Google",
    dontHaveAccount: "ليس لديك حساب؟",
    createNewAccountLink: "إنشاء حساب جديد",
    createAccount: "إنشاء حساب جديد",
    joinUsBookFirst: "انضم إلينا واحجز موعدك الأول",
    name: "الأسم",
    fullNameExample: "أحمد فواد المصري",
    email: "البريد الإلكتروني",
    emailExample: "ahmed@example.com",
    phone: "رقم الجوال",
    phoneExample2: "+966 50 123 4567",
    confirmPassword: "تأكيد كلمة المرور",
    enterStrongPassword: "أدخل كلمة مرور قوية",
    reenterPassword: "أعد إدخال كلمة المرور",
    creatingAccount: "جاري إنشاء الحساب...",
    signupWithGoogle: "تسجيل عبر Google",
    alreadyHaveAccount: "لديك حساب بالفعل؟",
    loginLink: "تسجيل الدخول",

    // Booking System
    selectService: "اختيار الخدمة",
    selectBarber: "اختيار الحلاق",
    selectDateAndTime: "اختر التاريخ والوقت",
    repeatOptions: "خيارات التكرار",
    bookingConfirmation: "تأكيد الحجز",
    bookingComplete: "تم الحجز",
    step: "الخطوة",
    of: "من",
    mainPage: "الصفحة الرئيسية",

    // Service Selection
    selectRequiredService: "اختر الخدمة المطلوبة",
    numberOfPeople: "عدد الأشخاص",
    onePerson: "شخص واحد",
    people: "أشخاص",
    pricePerPerson: "سيتم حساب السعر لكل شخص على حدة",
    noServicesAvailable: "لا توجد خدمات متاحة حالياً",

    // Date & Time Selection
    selectDate: "اختر التاريخ",
    selectTime: "اختر الوقت",
    noAvailableSlots: "لا توجد أوقات متاحة لهذا اليوم",
    wantToRepeat: "هل تريد تكرار الحجز؟",

    // Repeat Options
    repeatAppointment: "تكرار الموعد",
    wantToRepeatQuestion: "هل تريد تكرار هذا الموعد؟",
    selectedAppointment: "الموعد المحدد:",
    repeatOptionsTitle: "خيارات التكرار:",
    singleAppointment: "موعد واحد فقط",
    singleAppointmentDesc: "حجز موعد واحد بدون تكرار",
    repeatAppointmentOption: "تكرار الموعد",
    repeatAppointmentDesc: "حجز مواعيد متكررة بفترات منتظمة",
    repeatSettings: "إعدادات التكرار:",
    every: "كل:",
    unit: "الوحدة:",
    day: "يوم",
    week: "أسبوع",
    month: "شهر",
    numberOfTimes: "عدد المرات:",
    appointmentsPreview: "معاينة المواعيد:",
    totalCost: "المجموع الكلي:",
    appointment: "موعد",
    person: "شخص",

    // Booking Confirmation
    confirmBooking: "تأكيد الحجز",
    reviewBeforeConfirm: "راجع تفاصيل موعدك قبل التأكيد",
    bookingSummary: "ملخص الحجز",
    selectedService: "الخدمة المختارة:",
    duration: "المدة",
    totalPrice: "السعر الإجمالي",
    repeatInfo: "تكرار الموعد",
    repeatDates: "مواعيد التكرار:",
    additionalNotes: "ملاحظات إضافية (اختياري)",
    notesPlaceholder: "أضف أي ملاحظات أو طلبات خاصة...",
    bookingInProgress: "جاري الحجز...",
    appointmentBookedSuccess: "تم حجز الموعد بنجاح!",
    appointmentsBookedSuccess: "تم حجز المواعيد بنجاح!",
    appointmentBookingError: "حدث خطأ في حجز الموعد. يرجى المحاولة مرة أخرى.",

    // Booking Success
    bookingSuccessful: "تم حجز موعدك بنجاح!",
    thankYouSeeYouSoon: "شكراً لك، سنراك قريباً في صالوننا",
    appointmentDetails: "تفاصيل موعدك",
    service: "الخدمة:",
    date: "التاريخ:",
    time: "الوقت:",
    total: "المجموع:",
    importantReminder: "تذكير مهم:",
    arriveEarly: "احضر قبل 10 دقائق من موعدك",
    cancelModify: "للإلغاء أو التعديل، اتصل بنا قبل 24 ساعة على الأقل",
    backToHome: "العودة للرئيسية",
    myAppointments: "مواعيدي",
    contactUs: "اتصل بنا",

    // Profile
    personalProfile: "الملف الشخصي",
    totalAppointments: "إجمالي المواعيد",
    completedAppointments: "مواعيد مكتملة",
    pendingAppointments: "مواعيد معلقة",
    totalSpent: "إجمالي الإنفاق",
    editProfile: "تعديل الملف",
    changePassword: "تغيير كلمة المرور",
    editPersonalProfile: "تعديل الملف الشخصي",
    currentPassword: "كلمة المرور الحالية",
    newPassword: "كلمة المرور الجديدة",
    confirmNewPassword: "تأكيد كلمة المرور الجديدة",
    saveChanges: "حفظ التغييرات",
    upcomingAppointments: "المواعيد القادمة",
    noUpcomingAppointments: "لا توجد مواعيد قادمة",
    bookNewAppointment: "احجز موعد جديد",
    appointmentHistory: "سجل المواعيد",
    noAppointmentHistory: "لا يوجد سجل مواعيد",
    historyWillAppear: "ستظهر هنا المواعيد المكتملة",
    profilePictureUrl: "رابط الصورة الشخصية",
    passwordsNotMatch: "كلمات المرور غير متطابقة",
    passwordChangedSuccess: "تم تغيير كلمة المرور بنجاح",
    passwordChangeError: "حدث خطأ في تغيير كلمة المرور",
    appointmentUpdatedSuccess: "تم تحديث الموعد بنجاح",
    appointmentUpdateError: "حدث خطأ في تحديث الموعد",

    // Dashboard
    overview: "نظرة عامة",
    appointments: "المواعيد",
    customers: "العملاء",
    barbers: "الحلاقين",
    analytics: "التحليلات",
    timeManagement: "إدارة الأوقات",
    totalRevenue: "إجمالي الإيرادات",
    todayAppointments: "مواعيد اليوم",
    totalCustomers: "إجمالي العملاء",
    monthlyRevenue: "الإيرادات الشهرية",
    quickActions: "إجراءات سريعة",
    manageAppointments: "إدارة المواعيد",
    viewManageAllAppointments: "عرض وإدارة جميع المواعيد",
    manageCustomers: "إدارة العملاء",
    viewCustomerInfo: "عرض معلومات العملاء",
    manageServices: "إدارة الخدمات",
    addEditServices: "إضافة وتعديل الخدمات",
    salonOverview: "إليك نظرة عامة على أداء الصالون",

    // Time Management
    workingHoursSettings: "إعدادات أوقات العمل",
    enable: "تفعيل",
    openTime: "وقت الفتح",
    closeTime: "وقت الإغلاق",
    slotDuration: "مدة الموعد بالدقائق",
    breakTime: "وقت الاستراحة",
    saveSettings: "حفظ الإعدادات",

    // Days of week
    sunday: "الأحد",
    monday: "الاثنين",
    tuesday: "الثلاثاء",
    wednesday: "الأربعاء",
    thursday: "الخميس",
    friday: "الجمعة",
    saturday: "السبت",

    // Months
    january: "يناير",
    february: "فبراير",
    march: "مارس",
    april: "أبريل",
    may: "مايو",
    june: "يونيو",
    july: "يوليو",
    august: "أغسطس",
    september: "سبتمبر",
    october: "أكتوبر",
    november: "نوفمبر",
    december: "ديسمبر",

    // Status
    confirmed: "مؤكد",
    pending: "في الانتظار",
    completed: "مكتمل",
    cancelled: "ملغي",
    inProgress: "جاري التنفيذ",
    noShow: "لم يحضر",
    active: "نشط",
    inactive: "غير نشط",
    blocked: "محظور",

    // Footer
    quickLinks: "روابط سريعة",
    ourServices: "خدماتنا",
    contactInfo: "معلومات التواصل",
    allRightsReserved: "جميع الحقوق محفوظة.",

    // Loading and Messages
    loadingData: "جاري تحميل البيانات...",
    errorLoadingData: "حدث خطأ في تحميل البيانات",
    noDataAvailable: "لا توجد بيانات متاحة",
    operationSuccessful: "تمت العملية بنجاح",
    operationFailed: "فشلت العملية",
    pleaseWait: "يرجى الانتظار...",
    tryAgain: "حاول مرة أخرى",
  },
  en: {
    // Navigation
    home: "Home",
    services: "Services",
    booking: "Book Appointment",
    login: "Login",
    register: "Register",
    profile: "Profile",
    dashboard: "Dashboard",
    logout: "Logout",

    // Common
    continue: "Continue",
    cancel: "Cancel",
    save: "Save",
    edit: "Edit",
    delete: "Delete",
    confirm: "Confirm",
    loading: "Loading...",
    next: "Next",
    previous: "Previous",
    today: "Today",
    yes: "Yes",
    no: "No",
    close: "Close",
    submit: "Submit",
    search: "Search",
    filter: "Filter",
    add: "Add",
    update: "Update",
    remove: "Remove",
    view: "View",
    back: "Back",
    welcome: "Welcome",
    with: "with",
    for: "for",
    times: "times",
    appointments: "appointments",

    // Home
    heroTitle: "Best Barber Shop in Town",
    heroSubtitle:
      "Book your appointment now and enjoy the best haircut and grooming services",
    bookNow: "Book Now",
    readyForBestHaircut: "Ready for the best haircut?",
    bookNowEnjoyService:
      "Book your appointment now and enjoy exceptional service",
    myBookings: "My Bookings",
    createNewAccount: "Create New Account",
    enterPhoneNumber: "Enter your phone number:",
    phoneExample: "Example: 0591234567",
    phoneRequired: "Please enter phone number",
    phoneInvalid: "Invalid phone number (example: 0591234567)",
    phoneUpdatedSuccess: "Phone number updated successfully",
    send: "Send",

    // Services
    servicesTitle: "Our Premium Services",
    servicesSubtitle:
      "Discover a wide range of specialized haircut and grooming services",
    allServices: "All Services",
    haircut: "Haircut",
    beard: "Beard Trim",
    styling: "Hair Styling",
    treatment: "Hair Treatment",
    package: "Special Packages",
    minutes: "minutes",
    currency: "NIS",
    popularService: "Popular Service",
    noServicesInCategory: "No services in this category currently",
    didntFindWhatLookingFor: "Didn't find what you're looking for?",
    contactUsHelp:
      "Contact us and we'll help you find the right service for you",
    bookFreeConsultation: "Book Free Consultation",
    callUsNow: "Call Us Now",

    // Authentication
    welcomeBack: "Welcome Back",
    loginToAccount: "Sign in to access your account",
    username: "Username",
    enterUsername: "Enter username",
    password: "Password",
    enterPassword: "Enter password",
    loggingIn: "Logging in...",
    loginWithGoogle: "Login with Google",
    dontHaveAccount: "Don't have an account?",
    createNewAccountLink: "Create new account",
    createAccount: "Create New Account",
    joinUsBookFirst: "Join us and book your first appointment",
    name: "Name",
    fullNameExample: "John Doe",
    email: "Email",
    emailExample: "john@example.com",
    phone: "Phone Number",
    phoneExample2: "+1 555 123 4567",
    confirmPassword: "Confirm Password",
    enterStrongPassword: "Enter a strong password",
    reenterPassword: "Re-enter password",
    creatingAccount: "Creating account...",
    signupWithGoogle: "Sign up with Google",
    alreadyHaveAccount: "Already have an account?",
    loginLink: "Login",

    // Booking System
    selectService: "Select Service",
    selectBarber: "Select Barber",
    selectDateAndTime: "Select Date & Time",
    repeatOptions: "Repeat Options",
    bookingConfirmation: "Booking Confirmation",
    bookingComplete: "Booking Complete",
    step: "Step",
    of: "of",
    mainPage: "Main Page",

    // Service Selection
    selectRequiredService: "Select Required Service",
    numberOfPeople: "Number of People",
    onePerson: "one person",
    people: "people",
    pricePerPerson: "Price will be calculated per person",
    noServicesAvailable: "No services available currently",

    // Date & Time Selection
    selectDate: "Select Date",
    selectTime: "Select Time",
    noAvailableSlots: "No available slots for this day",
    wantToRepeat: "Want to repeat booking?",

    // Repeat Options
    repeatAppointment: "Repeat Appointment",
    wantToRepeatQuestion: "Do you want to repeat this appointment?",
    selectedAppointment: "Selected Appointment:",
    repeatOptionsTitle: "Repeat Options:",
    singleAppointment: "Single appointment only",
    singleAppointmentDesc: "Book one appointment without repetition",
    repeatAppointmentOption: "Repeat appointment",
    repeatAppointmentDesc: "Book recurring appointments at regular intervals",
    repeatSettings: "Repeat Settings:",
    every: "Every:",
    unit: "Unit:",
    day: "day",
    week: "week",
    month: "month",
    numberOfTimes: "Number of times:",
    appointmentsPreview: "Appointments Preview:",
    totalCost: "Total Cost:",
    appointment: "appointment",
    person: "person",

    // Booking Confirmation
    confirmBooking: "Confirm Booking",
    reviewBeforeConfirm: "Review your appointment details before confirming",
    bookingSummary: "Booking Summary",
    selectedService: "Selected Service:",
    duration: "Duration",
    totalPrice: "Total Price",
    repeatInfo: "Repeat Information",
    repeatDates: "Repeat Dates:",
    additionalNotes: "Additional Notes (optional)",
    notesPlaceholder: "Add any notes or special requests...",
    bookingInProgress: "Booking in progress...",
    appointmentBookedSuccess: "Appointment booked successfully!",
    appointmentsBookedSuccess: "Appointments booked successfully!",
    appointmentBookingError: "Error booking appointment. Please try again.",

    // Booking Success
    bookingSuccessful: "Your appointment has been booked successfully!",
    thankYouSeeYouSoon: "Thank you, we'll see you soon at our salon",
    appointmentDetails: "Your Appointment Details",
    service: "Service:",
    date: "Date:",
    time: "Time:",
    total: "Total:",
    importantReminder: "Important Reminder:",
    arriveEarly: "Arrive 10 minutes before your appointment",
    cancelModify:
      "To cancel or modify, contact us at least 24 hours in advance",
    backToHome: "Back to Home",
    myAppointments: "My Appointments",
    contactUs: "Contact Us",

    // Profile
    personalProfile: "Personal Profile",
    totalAppointments: "Total Appointments",
    completedAppointments: "Completed Appointments",
    pendingAppointments: "Pending Appointments",
    totalSpent: "Total Spent",
    editProfile: "Edit Profile",
    changePassword: "Change Password",
    editPersonalProfile: "Edit Personal Profile",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmNewPassword: "Confirm New Password",
    saveChanges: "Save Changes",
    upcomingAppointments: "Upcoming Appointments",
    noUpcomingAppointments: "No upcoming appointments",
    bookNewAppointment: "Book New Appointment",
    appointmentHistory: "Appointment History",
    noAppointmentHistory: "No appointment history",
    historyWillAppear: "Completed appointments will appear here",
    profilePictureUrl: "Profile Picture URL",
    passwordsNotMatch: "Passwords do not match",
    passwordChangedSuccess: "Password changed successfully",
    passwordChangeError: "Error changing password",
    appointmentUpdatedSuccess: "Appointment updated successfully",
    appointmentUpdateError: "Error updating appointment",

    // Dashboard
    overview: "Overview",
    appointments: "Appointments",
    customers: "Customers",
    barbers: "Barbers",
    analytics: "Analytics",
    timeManagement: "Time Management",
    totalRevenue: "Total Revenue",
    todayAppointments: "Today's Appointments",
    totalCustomers: "Total Customers",
    monthlyRevenue: "Monthly Revenue",
    quickActions: "Quick Actions",
    manageAppointments: "Manage Appointments",
    viewManageAllAppointments: "View and manage all appointments",
    manageCustomers: "Manage Customers",
    viewCustomerInfo: "View customer information",
    manageServices: "Manage Services",
    addEditServices: "Add and edit services",
    salonOverview: "here's an overview of the salon's performance",

    // Time Management
    workingHoursSettings: "Working Hours Settings",
    enable: "Enable",
    openTime: "Open Time",
    closeTime: "Close Time",
    slotDuration: "Slot Duration in Minutes",
    breakTime: "Break Time",
    saveSettings: "Save Settings",

    // Days of week
    sunday: "Sunday",
    monday: "Monday",
    tuesday: "Tuesday",
    wednesday: "Wednesday",
    thursday: "Thursday",
    friday: "Friday",
    saturday: "Saturday",

    // Months
    january: "January",
    february: "February",
    march: "March",
    april: "April",
    may: "May",
    june: "June",
    july: "July",
    august: "August",
    september: "September",
    october: "October",
    november: "November",
    december: "December",

    // Status
    confirmed: "Confirmed",
    pending: "Pending",
    completed: "Completed",
    cancelled: "Cancelled",
    inProgress: "In Progress",
    noShow: "No Show",
    active: "Active",
    inactive: "Inactive",
    blocked: "Blocked",

    // Footer
    quickLinks: "Quick Links",
    ourServices: "Our Services",
    contactInfo: "Contact Information",
    allRightsReserved: "All rights reserved.",

    // Loading and Messages
    loadingData: "Loading data...",
    errorLoadingData: "Error loading data",
    noDataAvailable: "No data available",
    operationSuccessful: "Operation successful",
    operationFailed: "Operation failed",
    pleaseWait: "Please wait...",
    tryAgain: "Try again",
  },
  he: {
    // Navigation
    home: "בית",
    services: "שירותים",
    booking: "קביעת תור",
    login: "התחברות",
    register: "הרשמה",
    profile: "פרופיל",
    dashboard: "לוח בקרה",
    logout: "התנתקות",

    // Common
    continue: "המשך",
    cancel: "ביטול",
    save: "שמירה",
    edit: "עריכה",
    delete: "מחיקה",
    confirm: "אישור",
    loading: "טוען...",
    next: "הבא",
    previous: "הקודם",
    today: "היום",
    yes: "כן",
    no: "לא",
    close: "סגירה",
    submit: "שליחה",
    search: "חיפוש",
    filter: "סינון",
    add: "הוספה",
    update: "עדכון",
    remove: "הסרה",
    view: "צפייה",
    back: "חזרה",
    welcome: "ברוך הבא",
    with: "עם",
    for: "למשך",
    times: "פעמים",
    appointments: "תורים",

    // Home
    heroTitle: "מספרה הטובה ביותר בעיר",
    heroSubtitle: "קבע תור עכשיו ותיהנה משירותי התספורת והטיפוח הטובים ביותר",
    bookNow: "קבע תור",
    readyForBestHaircut: "מוכן לתספורת הטובה ביותר?",
    bookNowEnjoyService: "קבע תור עכשיו ותיהנה משירות יוצא דופן",
    myBookings: "התורים שלי",
    createNewAccount: "יצירת חשבון חדש",
    enterPhoneNumber: "הכנס את מספר הטלפון שלך:",
    phoneExample: "דוגמה: 0591234567",
    phoneRequired: "אנא הכנס מספר טלפון",
    phoneInvalid: "מספר טלפון לא תקין (דוגמה: 0591234567)",
    phoneUpdatedSuccess: "מספר הטלפון עודכן בהצלחה",
    send: "שלח",

    // Services
    servicesTitle: "השירותים המובחרים שלנו",
    servicesSubtitle: "גלה מגוון רחב של שירותי תספורת וטיפוח מתמחים",
    allServices: "כל השירותים",
    haircut: "תספורת",
    beard: "עיצוב זקן",
    styling: "עיצוב שיער",
    treatment: "טיפולי שיער",
    package: "חבילות מיוחדות",
    minutes: "דקות",
    currency: "ש״ח",
    popularService: "שירות פופולרי",
    noServicesInCategory: "אין שירותים בקטגוריה זו כרגע",
    didntFindWhatLookingFor: "לא מצאת את מה שחיפשת?",
    contactUsHelp: "צור קשר ונעזור לך למצוא את השירות המתאים",
    bookFreeConsultation: "קבע ייעוץ חינם",
    callUsNow: "התקשר אלינו עכשיו",

    // Authentication
    welcomeBack: "ברוך שובך",
    loginToAccount: "התחבר כדי לגשת לחשבון שלך",
    username: "שם משתמש",
    enterUsername: "הכנס שם משתמש",
    password: "סיסמה",
    enterPassword: "הכנס סיסמה",
    loggingIn: "מתחבר...",
    loginWithGoogle: "התחברות עם Google",
    dontHaveAccount: "אין לך חשבון?",
    createNewAccountLink: "צור חשבון חדש",
    createAccount: "יצירת חשבון חדש",
    joinUsBookFirst: "הצטרף אלינו וקבע את התור הראשון שלך",
    name: "שם",
    fullNameExample: "יוחנן כהן",
    email: "אימייל",
    emailExample: "yohanan@example.com",
    phone: "מספר טלפון",
    phoneExample2: "+972 50 123 4567",
    confirmPassword: "אישור סיסמה",
    enterStrongPassword: "הכנס סיסמה חזקה",
    reenterPassword: "הכנס שוב את הסיסמה",
    creatingAccount: "יוצר חשבון...",
    signupWithGoogle: "הרשמה עם Google",
    alreadyHaveAccount: "כבר יש לך חשבון?",
    loginLink: "התחברות",

    // Booking System
    selectService: "בחירת שירות",
    selectBarber: "בחירת ספר",
    selectDateAndTime: "בחירת תאריך ושעה",
    repeatOptions: "אפשרויות חזרה",
    bookingConfirmation: "אישור הזמנה",
    bookingComplete: "הזמנה הושלמה",
    step: "שלב",
    of: "מתוך",
    mainPage: "עמוד ראשי",

    // Service Selection
    selectRequiredService: "בחר את השירות הנדרש",
    numberOfPeople: "מספר אנשים",
    onePerson: "אדם אחד",
    people: "אנשים",
    pricePerPerson: "המחיר יחושב לכל אדם בנפרד",
    noServicesAvailable: "אין שירותים זמינים כרגע",

    // Date & Time Selection
    selectDate: "בחר תאריך",
    selectTime: "בחר שעה",
    noAvailableSlots: "אין זמנים פנויים ליום זה",
    wantToRepeat: "רוצה לחזור על ההזמנה?",

    // Repeat Options
    repeatAppointment: "חזרה על התור",
    wantToRepeatQuestion: "האם אתה רוצה לחזור על התור הזה?",
    selectedAppointment: "התור שנבחר:",
    repeatOptionsTitle: "אפשרויות חזרה:",
    singleAppointment: "תור יחיד בלבד",
    singleAppointmentDesc: "הזמנת תור אחד ללא חזרה",
    repeatAppointmentOption: "חזרה על התור",
    repeatAppointmentDesc: "הזמנת תורים חוזרים במרווחים קבועים",
    repeatSettings: "הגדרות חזרה:",
    every: "כל:",
    unit: "יחידה:",
    day: "יום",
    week: "שבוע",
    month: "חודש",
    numberOfTimes: "מספר פעמים:",
    appointmentsPreview: "תצוגה מקדימה של תורים:",
    totalCost: "עלות כוללת:",
    appointment: "תור",
    person: "אדם",

    // Booking Confirmation
    confirmBooking: "אישור הזמנה",
    reviewBeforeConfirm: "סקור את פרטי התור שלך לפני האישור",
    bookingSummary: "סיכום הזמנה",
    selectedService: "השירות שנבחר:",
    duration: "משך זמן",
    totalPrice: "מחיר כולל",
    repeatInfo: "מידע על חזרה",
    repeatDates: "תאריכי חזרה:",
    additionalNotes: "הערות נוספות (אופציונלי)",
    notesPlaceholder: "הוסף הערות או בקשות מיוחדות...",
    bookingInProgress: "הזמנה בתהליך...",
    appointmentBookedSuccess: "התור הוזמן בהצלחה!",
    appointmentsBookedSuccess: "התורים הוזמנו בהצלחה!",
    appointmentBookingError: "שגיאה בהזמנת התור. אנא נסה שוב.",

    // Booking Success
    bookingSuccessful: "התור שלך הוזמן בהצלחה!",
    thankYouSeeYouSoon: "תודה לך, נתראה בקרוב במספרה שלנו",
    appointmentDetails: "פרטי התור שלך",
    service: "שירות:",
    date: "תאריך:",
    time: "שעה:",
    total: "סה״כ:",
    importantReminder: "תזכורת חשובה:",
    arriveEarly: "הגע 10 דקות לפני התור שלך",
    cancelModify: "לביטול או שינוי, צור קשר לפחות 24 שעות מראש",
    backToHome: "חזרה לבית",
    myAppointments: "התורים שלי",
    contactUs: "צור קשר",

    // Profile
    personalProfile: "פרופיל אישי",
    totalAppointments: "סך התורים",
    completedAppointments: "תורים שהושלמו",
    pendingAppointments: "תורים ממתינים",
    totalSpent: "סך הוצאות",
    editProfile: "עריכת פרופיל",
    changePassword: "שינוי סיסמה",
    editPersonalProfile: "עריכת פרופיל אישי",
    currentPassword: "סיסמה נוכחית",
    newPassword: "סיסמה חדשה",
    confirmNewPassword: "אישור סיסמה חדשה",
    saveChanges: "שמירת שינויים",
    upcomingAppointments: "תורים קרובים",
    noUpcomingAppointments: "אין תורים קרובים",
    bookNewAppointment: "קבע תור חדש",
    appointmentHistory: "היסטוריית תורים",
    noAppointmentHistory: "אין היסטוריית תורים",
    historyWillAppear: "תורים שהושלמו יופיעו כאן",
    profilePictureUrl: "כתובת תמונת פרופיל",
    passwordsNotMatch: "הסיסמאות אינן תואמות",
    passwordChangedSuccess: "הסיסמה שונתה בהצלחה",
    passwordChangeError: "שגיאה בשינוי הסיסמה",
    appointmentUpdatedSuccess: "התור עודכן בהצלחה",
    appointmentUpdateError: "שגיאה בעדכון התור",

    // Dashboard
    overview: "סקירה כללית",
    appointments: "תורים",
    customers: "לקוחות",
    barbers: "ספרים",
    analytics: "אנליטיקה",
    timeManagement: "ניהול זמנים",
    totalRevenue: "סך הכנסות",
    todayAppointments: "תורי היום",
    totalCustomers: "סך לקוחות",
    monthlyRevenue: "הכנסות חודשיות",
    quickActions: "פעולות מהירות",
    manageAppointments: "ניהול תורים",
    viewManageAllAppointments: "צפייה וניהול כל התורים",
    manageCustomers: "ניהול לקוחות",
    viewCustomerInfo: "צפייה במידע לקוחות",
    manageServices: "ניהול שירותים",
    addEditServices: "הוספה ועריכה של שירותים",
    salonOverview: "הנה סקירה כללית על ביצועי המספרה",

    // Time Management
    workingHoursSettings: "הגדרות שעות עבודה",
    enable: "הפעלה",
    openTime: "שעת פתיחה",
    closeTime: "שעת סגירה",
    slotDuration: "משך זמן תור בדקות",
    breakTime: "זמן הפסקה",
    saveSettings: "שמירת הגדרות",

    // Days of week
    sunday: "ראשון",
    monday: "שני",
    tuesday: "שלישי",
    wednesday: "רביעי",
    thursday: "חמישי",
    friday: "שישי",
    saturday: "שבת",

    // Months
    january: "ינואר",
    february: "פברואר",
    march: "מרץ",
    april: "אפריל",
    may: "מאי",
    june: "יוני",
    july: "יולי",
    august: "אוגוסט",
    september: "ספטמבר",
    october: "אוקטובר",
    november: "נובמבר",
    december: "דצמבר",

    // Status
    confirmed: "מאושר",
    pending: "ממתין",
    completed: "הושלם",
    cancelled: "בוטל",
    inProgress: "בתהליך",
    noShow: "לא הגיע",
    active: "פעיל",
    inactive: "לא פעיל",
    blocked: "חסום",

    // Footer
    quickLinks: "קישורים מהירים",
    ourServices: "השירותים שלנו",
    contactInfo: "פרטי התקשרות",
    allRightsReserved: "כל הזכויות שמורות.",

    // Loading and Messages
    loadingData: "טוען נתונים...",
    errorLoadingData: "שגיאה בטעינת נתונים",
    noDataAvailable: "אין נתונים זמינים",
    operationSuccessful: "הפעולה הצליחה",
    operationFailed: "הפעולה נכשלה",
    pleaseWait: "אנא המתן...",
    tryAgain: "נסה שוב",
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState("ar");
  const [direction, setDirection] = useState("rtl");

  const changeLanguage = (lang) => {
    setLanguage(lang);
    setDirection(lang === "ar" || lang === "he" ? "rtl" : "ltr");
    document.documentElement.dir =
      lang === "ar" || lang === "he" ? "rtl" : "ltr";
    document.documentElement.lang = lang;
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  const value = {
    language,
    direction,
    changeLanguage,
    t,
  };

  return (
    <LanguageContext.Provider value={value}>
      <div className={direction}>{children}</div>
    </LanguageContext.Provider>
  );
};
